networks:
  mynetworkapi: {}

services:
  mysqldocker:
    container_name: mysql-docker2
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=MyPassword*1234
      - MYSQL_DATABASE=Store
      - MYSQL_USER=storeuser
      - MYSQL_PASSWORD=storepass
    networks:
      - mynetworkapi

  store:
    build:
      context: .
      dockerfile: Store/Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=mysqldocker;Database=Store;User=storeuser;Password=storepass;
    depends_on:
      - mysqldocker
    ports:
      - 5001:8081
    networks:
      - mynetworkapi
